PS 130 Flexible campaigns
shopgate-professional-services/ext-dynamic-yield pull request #2
Opened 2024-07-02 08:32 UTC by patrick-scherer

## Flexible campaigns

Added optional parameter `requestOptions` to pipeline request

2024-07-03 12:54 UTC, fkloes requested changes

2024-07-03 12:54 UTC, fkloes commented on extension/lib/dynamicYield/Client.js
> +      if (campaignNames && campaignPageType) {
`campaignNames` will always be truthy, since the fallback is an empty array. in that case `this.campaigns` would be overwritten by an empty array. is this intended?

2024-07-03 12:54 UTC, fkloes commented on extension/lib/dynamicYield/Client.js
> +      if (context.type === 'product' && this.pageTypes.includes('PRODUCT')) {
i think it's very confusing that the `input` property of the pipeline step is called `context` inside this method.

2024-07-04 08:44 UTC, patrick-scherer commented on extension/lib/dynamicYield/Client.js
> +      if (campaignNames && campaignPageType) {
the length of `campaignNames` is now checked

2024-07-04 08:44 UTC, patrick-scherer commented on extension/lib/dynamicYield/Client.js
> +      if (context.type === 'product' && this.pageTypes.includes('PRODUCT')) {
renamed it to "input"

2024-07-16 13:41 UTC, fkloes requested changes

2024-07-16 13:41 UTC, fkloes commented on extension/lib/dynamicYield/Client.js
> +        const response = await this.request({ input }, bodyData, endpoint);
as discussed, please figure out, if we need to send the input object as query parameters with the request.
before you've send a parameter "context", now it's "input".

2024-08-06 09:02 UTC, merged